name: triplog 앱 배포
on:
  push:
    branches:
      - master
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      - name: JDK 17 설정
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven으로 빌드
        run: mvn clean package
      - name: 도커 이미지 빌드
        run: docker build -t clz2024sun/triplog:latest .
      - name: 도커 허브 로그인
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: 도커 이미지 도커 허브에 푸시
        run: docker push clz2024sun/triplog:latest

  deploy-mysql:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: EC2에 SSH 접속 및 MySQL 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 기존 MySQL 컨테이너 정리
            sudo docker stop mysql || true
            sudo docker rm mysql || true
            
            # 필요한 디렉토리 생성
            sudo mkdir -p /home/ec2-user/mysql-data
            
            # MySQL 커스텀 설정 파일 생성
            sudo tee /home/ec2-user/mysql-config.cnf << EOF
            [mysqld]
            bind-address = 0.0.0.0
            port = 3306
            character-set-server = utf8mb4
            collation-server = utf8mb4_unicode_ci
            EOF
            
            # MySQL 컨테이너 실행 (데이터 영구 보존)
            sudo docker run -d \
              --name mysql \
              -p 3306:3306 \
              -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
              -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
              -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
              -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -v /home/ec2-user/mysql-data:/var/lib/mysql \
              -v /home/ec2-user/mysql-config.cnf:/etc/mysql/conf.d/custom.cnf \
              mysql:8.0.38
            
            # 방화벽 포트 개방
            sudo firewall-cmd --permanent --add-port=3306/tcp || true
            sudo firewall-cmd --reload || true

  deploy-application:
    needs: deploy-mysql
    runs-on: ubuntu-latest
    steps:
      - name: EC2에 SSH 접속 및 애플리케이션 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 필요한 디렉토리 생성
            sudo mkdir -p /home/ec2-user/upload
            
            # 기존 애플리케이션 컨테이너 정리
            sudo docker stop triplog || true
            sudo docker rm triplog || true

            # 애플리케이션 컨테이너 실행
            sudo docker run -d \
              --name triplog \
              -p 9000:9000 \
              --network triplog-network \
              -e DATABASE_URL=mysql://triplog-network:3306/triplog_db?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8 \
              -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -v /home/ec2-user/upload:/app/upload \
              clz2024sun/triplog:latest